version: 2
general_options: &general_options
  docker:
    - image: maxmcd/deno
  working_directory: ~/repo
jobs:
  checkout:
    <<: *general_options
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  lint:
    <<: *general_options
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Lint code
          command: deno --allow-read --allow-write --allow-run https://deno.land/x/std/prettier/main.ts ./src --check
  test:
    <<: *general_options
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Test code
          command: deno ./test.ts
workflows:
  version: 2
  default:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - test:
          requires:
            - checkout
